### ISSUE TITLE
关于复现过程中遇到的问题

### ISSUE THREAD

**Issue by meve1216** [lswzjuer/NAS-WDAN#2]
在单一数据集CVC进行搜索训练时，发现其权值损失和架构损失都非常的大，请问作者您有这样的问题吗？是何原因呢？

**Comment by lswzjuer** [comment]
CVC数据集在数据分布和样本数量上与其他两个数据机均差别较大，SuperNet在设计的时候是综合考虑三个数据集的规模设计的，针对单一数据集CVC进行搜索训练如果想要降低权值损失和架构损失的绝对数值，可总loss权重以及权值损失和架构损失的权重相对值，可以收敛。

**Comment by meve1216** [comment]
> CVC数据集在数据分布和样本数量上与其他两个数据机均差别较大，SuperNet在设计的时候是综合考虑三个数据集的规模设计的，针对单一数据集CVC进行搜索训练如果想要降低权值损失和架构损失的绝对数值，可总loss权重以及权值损失和架构损失的权重相对值，可以收敛。

您好！谢谢您的回答。后来针对损失值较大进行的分析之后，我将datasets文件夹中的cvc.py文件中的tr.FixedResize(size=(192,256)) 均修改为（256，256）之后 损失值变得收敛。
